# -*- coding: utf-8 -*-
translationContributors = ['TheMikirog (idea, visuals, coding, characters, most content)\n'
						   '        SoK (most maps, some characters, small changes, general testing)\n'
						   '        EKFH (coding assistance)\n'
                           '        Mrmaxmeier (Blender plugin for BombSquad models, quick-game button)\n'
                           '        PG I (Stickies! gamemode)\n'
                           '        FightBiscuit (Arms Race redux)\n'
                           '        Froshlee (Get the Target gamemode that I modified for JRMP)\n'
                           '        Manny Headset Gamer (Klaymen model)\n'
                           '        Everyone that supports the modpack by playing it!\n']
languageNamesTranslated = {'Turkish':'Türkçe','Korean':'한국어','Hungarian':'Magyar','French':'Français','Russian':'Русский','Gibberish':'Gibberish','Italian':'Italiano','Czech':'Čeština','German':'Deutsch','Persian':'فارسی','Polish':'Polski','Swedish':'Svenska','Romanian':'Română','Belarussian':'Беларуская','Dutch':'Nederlands','Danish':'Dansk','Indonesian':'Insdofsif','Spanish':'Español','Esperanto':'Esperanto','Croatian':'Hrvatski','Portuguese':'Português','Chinese':'中文','Japanese':'日本語'}
splashText = ['Now with 100% more footsies!',
              'Command Throw to victory!',
              'Pinecone Master Race!',
              '11 herbs and spices',
              'Behind you...',
              'He\'s wearing an orange cap.',
              'Feels like 1984',
              'Nostalgia overload!',
              'Also try Bombing Over It!',
              'Oh! It\'s you!',
              'Blue is the new black!',
              'Nightmare is for babies!',
              'Wombo Combo!',
              'Evidence.zip',
              'Hopefully it has been worth the wait!',
              '1v1 Elim, Rampage, comp powerups!',
              'delin.ogg',
              'Have you heard about my modpack?',
              'Just don\'t get grabbed!',
              'Mountains of salt included!',
              'Gamepad highly recommended!',
              'BONK!',
              '360 running jump punch!',
              'ok boomer',
              'Why are you running!?',
              'After 10 000 years of development...',
              'From Poland with love',
              'Did you ever watch BombStory?',
              'Luck x Skill = Victory',
              'Fiddlesticks!',
              'Also known as BombSquad 2',
              '2.7 is finally here!',
              'Knock knock',
              'Dum dum dum, dum dum dum dum dum duuum',
              'Ninja with a green mask',
              'Maximum Overdrive!',
              'Fat Pigs are endangered.',
              'Mother of all modpacks!',
              'Quality over quantity!',
              'If you can\'t bomb, dash!',
              'Impact Bombs are OP',
              'It\'s alive! It\'s alive!',
              'a.k.a Brutal BombSquad',
              'Slapstick Gold!',
              'Three-hit punch combos!',
              'Shoutout to... who?',
              'Nothing is impossible!',
              'Don\'t blame me, im a fricking code!',
              'Shiny Bots are common in (6am, pm) or (12am, pm)!',
              'Risk vs Reward',
              'Now >4 years old!',
              'H.D.K.N',
              'S.P.A.M',
              'Ohh, what? OHH!',
              '[insert quote here]',
              'Glowing colors suck.',
              'Chaos and Destruction',
              'Visceral Feelings',
              'Do you know who ate all of the donuts?',
              'Casserole Ruiner',
              'Feldman\'s Yeast',
              'State of the art explosions!']